# Generated by Django 5.2.8 on 2025-12-06 16:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoReservable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('zona_horaria', models.CharField(default='UTC', max_length=64)),
                ('capacidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('esta_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'programacion_recurso',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['esta_activo'], name='programacio_esta_ac_1062a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.DurationField(help_text='Duracion neta del servicio.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1))])),
                ('buffer_antes', models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('buffer_despues', models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('esta_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='scheduling.recursoreservable')),
            ],
            options={
                'db_table': 'programacion_servicio',
            },
        ),
        migrations.CreateModel(
            name='ReglaDisponibilidadRecurrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miercoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sabado'), (6, 'domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_disponibilidad', to='scheduling.recursoreservable')),
                ('servicio', models.ForeignKey(blank=True, help_text='Opcional: regla especifica para un servicio del recurso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_disponibilidad', to='scheduling.servicio')),
            ],
            options={
                'db_table': 'programacion_regla_disponibilidad',
                'ordering': ['recurso', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionDisponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('closed', 'cerrado'), ('open', 'abierto')], max_length=8)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_disponibilidad', to='scheduling.recursoreservable')),
                ('servicio', models.ForeignKey(blank=True, help_text='Opcional: excepcion especifica para un servicio del recurso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_disponibilidad', to='scheduling.servicio')),
            ],
            options={
                'db_table': 'programacion_excepcion_disponibilidad',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Referencia del evento/cliente.', max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('scheduled', 'agendada'), ('cancelled', 'cancelada')], default='scheduled', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ("producto", models.ForeignKey(blank=True, help_text="Producto asociado a la cita (opcional).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="citas", to="ecommerce.producto")),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='scheduling.recursoreservable')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='scheduling.servicio')),
            ],
            options={
                'db_table': 'programacion_cita',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['recurso', 'esta_activo'], name='programacio_recurso_f2dbe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('recurso', 'nombre'), name='uq_servicio_por_recurso'),
        ),
        migrations.AddIndex(
            model_name='regladisponibilidadrecurrente',
            index=models.Index(fields=['recurso', 'dia_semana', 'esta_activa'], name='programacio_recurso_5dedcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='regladisponibilidadrecurrente',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_regla_fin_despues_inicio'),
        ),
        migrations.AddConstraint(
            model_name='regladisponibilidadrecurrente',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__gte', models.F('vigente_desde')), ('vigente_hasta__isnull', True), ('vigente_desde__isnull', True), _connector='OR'), name='chk_regla_rango_fechas'),
        ),
        migrations.AddIndex(
            model_name='excepciondisponibilidad',
            index=models.Index(fields=['recurso', 'fecha'], name='programacio_recurso_44a974_idx'),
        ),
        migrations.AddIndex(
            model_name='excepciondisponibilidad',
            index=models.Index(fields=['recurso', 'fecha', 'tipo'], name='programacio_recurso_dd71c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='excepciondisponibilidad',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_excepcion_fin_despues_inicio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['recurso', 'inicio'], name='programacio_recurso_c94a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['recurso', 'estado'], name='programacio_recurso_45fdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['producto', 'inicio'], name='programacio_product_325fd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='chk_cita_fin_despues_inicio'),
        ),
    ]
