# Generated by Django 5.2.8 on 2025-12-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario comprador/cliente asociado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['pago_confirmado'], name='programacio_pago_co_444458_idx'),
        ),
    ]
