# Generated by Django 5.2.8 on 2025-12-06 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("scheduling", "0001_initial"),
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CART_CHECKOUT', 'checkout_carrito'), ('RESERVATION', 'reserva'), ('MANUAL', 'manual')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_events', to='scheduling.cita')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_events', to='commerce.order')),
                ("tienda", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sale_events", to="ecommerce.tienda")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_event',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('categoria_snapshot_id', models.IntegerField(blank=True, null=True)),
                ('categoria_snapshot_nombre', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sale_items", to="ecommerce.producto")),
                ('sale_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleevent')),
            ],
            options={
                'db_table': 'sales_item',
            },
        ),
        migrations.AddIndex(
            model_name='saleevent',
            index=models.Index(fields=['source'], name='sales_event_source_bdc240_idx'),
        ),
        migrations.AddIndex(
            model_name='saleevent',
            index=models.Index(fields=['tienda'], name='sales_event_tienda__9ce6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='uq_sale_por_order'),
        ),
        migrations.AddConstraint(
            model_name='saleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('cita__isnull', False)), fields=('cita',), name='uq_sale_por_cita'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale_event'], name='sales_item_sale_ev_b124ff_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['producto'], name='sales_item_product_2312c7_idx'),
        ),
    ]
